version: '3.4'

services:
  pokemondb:
    image: mongo

  api-mongodb:
    image: ${DOCKER_REGISTRY-}apimongodb
    build:
      context: Pokemon
      dockerfile: Dockerfile
  
volumes:
  mongo_data:
    